### ISSUE TITLE
Add a simple binary?

### ISSUE THREAD

**Issue by rauschma** [jspm/generator#98] opened 2022-01-11 13:15 UTC
I’m not sure if that is possible, but I’d find it useful if I could generate an import map like this:

```
npx @jspm/generator node_modules/
```

**Comment by fusionstrings** [comment] 2022-01-16 18:02
Did you mean, one importmap for every package in node_modules?

hypothetically considering following an entry point for the generated importmap for each package?

```js
import package from 'package'
```

**Comment by guybedford** [comment] 2022-07-13 01:41
Duplicate of https://github.com/jspm/generator/issues/64. There will eventually be a CLI relaunch when the timing is right.

**Closed by guybedford** 2022-07-13 01:41 UTC
