### ISSUE TITLE
 throw new JspmError(`${parentUrl}node_modules/${target.name} does not exist,

### ISSUE THREAD

**Issue by zengtiansheng** [jspm/generator#391] opened 2024-11-22 05:52 UTC
I use the pnpm package management tool in my project and use `nodemodules` as the`defaultProvider` to generate importmap. This is my sample code. 

```js
// package.json
{
  "name": "web-module-demo",
  "type": "module",
  "devDependencies": {
    "@jspm/generator": "^2.4.1"
  },
  "dependencies": {
    "lit": "^3.2.1"
  }
}
```

```js
// generator.js
import { Generator } from '@jspm/generator';
const generator = new Generator({
    env: ['production', 'browser', 'module'],
    defaultProvider: 'nodemodules',
});
await generator.install('lit');
console.log(JSON.stringify(generator.getMap(), null, 2));
```

I run `pnpm install && node generator.js` and get the following error:

```
node generator.js
file:///xxxx/demo/jspm-demo/generator.js
file:///xxxx/demo/jspm-demo/node_modules/.pnpm/@jspm+generator@2.4.1/node_modules/@jspm/generator/dist/generator-cbc17fc9.js:1716
            throw new JspmError(`${parentUrl}node_modules/${target.name} does not exist, try installing "${target.name}" with npm first via "npm install ${target.name}".`);
                  ^
JspmError: file:///xxxx/demo/jspm-demo/node_modules/lit/index.jsnode_modules/@lit/reactive-element does not exist, try installing "@lit/reactive-element" with npm first via "npm install @lit/reactive-element".
    at Resolver.resolveLatestTarget (file:///xxxx/demo/jspm-demo/node_modules/.pnpm/@jspm+generator@2.4.1/node_modules/@jspm/generator/dist/generator-cbc17fc9.js:1716:19)
    at async Installer.installTarget (file:///xxxx/demo/jspm-demo/node_modules/.pnpm/@jspm+generator@2.4.1/node_modules/@jspm/generator/dist/generator-cbc17fc9.js:2752:27)
    at async TraceMap.resolve (file:///xxxx/demo/jspm-demo/node_modules/.pnpm/@jspm+generator@2.4.1/node_modules/@jspm/generator/dist/generator-cbc17fc9.js:3234:27)
    at async TraceMap.visit (file:///xxxx/demo/jspm-demo/node_modules/.pnpm/@jspm+generator@2.4.1/node_modules/@jspm/generator/dist/generator-cbc17fc9.js:3024:26)
    at async file:///xxxx/demo/jspm-demo/node_modules/.pnpm/@jspm+generator@2.4.1/node_modules/@jspm/generator/dist/generator-cbc17fc9.js:3073:13
    at async Promise.all (index 0)
    at async TraceMap.visit (file:///xxxx/demo/jspm-demo/node_modules/.pnpm/@jspm+generator@2.4.1/node_modules/@jspm/generator/dist/generator-cbc17fc9.js:3068:9)
    at async file:///xxxx/demo/jspm-demo/node_modules/.pnpm/@jspm+generator@2.4.1/node_modules/@jspm/generator/dist/generator-cbc17fc9.js:4282:13
    at async Promise.all (index 0)
    at async Generator._install (file:///xxxx/demo/jspm-demo/node_modules/.pnpm/@jspm+generator@2.4.1/node_modules/@jspm/generator/dist/generator-cbc17fc9.js:4281:9) {
  jspmError: true,
  code: undefined
}
```

According to the error message, can I only use `npm` or `yarn` and not `pnpm`?

**Comment by guybedford** [comment] 2024-12-26 16:12
The path at `file:///xxxx/demo/jspm-demo/node_modules/lit/index.jsnode_modules/@lit/reactive-element` seems like it is incorrectly doing path manipulations in the nodemodules provider here.

This may or may not be pnpm specific, but sounds like a bug that could be fixed in that provider to me given there is a missing slash in the path handling.

**Comment by guybedford** [comment] 2024-12-27 09:53
This is not a bug after all - the issue is that you haven't installed @lit/reactive-element. I can correct the error message though.

**Closed** 2024-12-27 11:41 UTC

**Comment by ZengTianShengZ** [comment] 2025-01-08 09:19
I installed the lit package using pnpm. @lit/reactive-element is a sub-dependency of the lit package and does not need to be installed separately. The real reason should be that the sub-dependencies installed by pnpm are organized by symbolic link and hard link. @jspm/generator does not support searching for sub-dependencies through symbolic link, which results in an error.
https://github.com/jspm/generator/blob/047880cec7d112ba8828ef577fec2befe3d91385/src/providers/nodemodules.ts#L140

**Comment by guybedford** [comment] 2025-02-02 20:24
@zengtiansheng `node_modules/@lit/reactive-element` is the folder that must exist for this to resolve. If you can confirm that folder is symlinked correctly and you are still seeing the issue then I'm happy to reopen the bug, but that was not the case when I looked into this.
