### ISSUE TITLE
Non-deterministic resolution

### ISSUE THREAD

**Issue by vovacodes** [jspm/generator#85] opened 2021-11-20 18:49 UTC
Notice how `@babel/runtime/helpers/typeof`'s mapping randomly switches between `https://ga.jspm.io/npm:@babel/runtime@7.16.0/helpers/typeof.js` and `https://ga.jspm.io/npm:@babel/runtime@7.16.0/helpers/esm/typeof.js` 

https://user-images.githubusercontent.com/1524432/142737757-8803e41f-8b79-4398-a477-e71ad9e70818.mov

**Comment by guybedford** [comment] 2021-11-20 18:53
It is a known problem and is caused by "require" and "import" branches in the import map not having a well-defined "single solution". Determinism would be fixed by https://github.com/jspm/generator/issues/40. The question of which to use when "require" and "import" intersect (and these are the only conditions that do intersect within the same environment), could possibly be solved by always using one or the other and ensuring that is a fixed rule.

**Comment by guybedford** [comment] 2021-11-25 18:06
Resolved in https://github.com/jspm/generator/pull/86 by giving `"require"` precedence in conflicts.

**Closed by guybedford** 2021-11-25 18:06 UTC
